name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.89.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          toolchain: ${{ matrix.rust }}

      - name: Build workspace
        run: cargo build --workspace --verbose

      - name: Lint with clippy
        run: cargo clippy -p cli -p shared_lib --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --workspace --verbose
